#!/usr/bin/env python3
from pyfuturerestore.__main__ import main
from m1n1Exception import *

set_package_name("pyfuturerestore")

try:
	main()
except m1n1Exception as e:
	print(e)
